baseURL = ""
languageCode = "en-us"
title = "Security"
theme ="security"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "© 2020 Security."
description = "Security - Medigy"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "siegerts"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
